// Initial dropdown values + approver roster, sourced from the existing
// Apps Script form. Seeded into MongoDB once; admins manage via the UI after.

export const SEED_DEPARTMENTS = [
  "Admin",
  "Admin & Finance",
  "Agrilife",
  "Audit",
  "Customer Service",
  "Eurolab",
  "Finance",
  "Formulation & Qlty Assurance",
  "Human Resources",
  "IT",
  "Logistics",
  "Maintenance",
  "Marketing",
  "Operations",
  "Process and Inventory Control",
  "Production",
  "Production&Warehouse",
  "Purchasing",
  "QA",
  "Quality",
  "Sales",
  "Warehouse",
];

export const SEED_DOMESTIC_AIRPORTS = [
  "Bacolod",
  "Bohol",
  "Boracay (Caticlan)",
  "Butuan",
  "Cagayan de Oro",
  "Calbayog",
  "Camiguin",
  "Cauayan",
  "Cebu",
  "Clark",
  "Coron (Busuanga)",
  "Cotabato",
  "Davao",
  "Dipolog",
  "Dumaguete",
  "General Santos",
  "Iloilo",
  "Kalibo",
  "Legazpi",
  "Manila",
  "Masbate",
  "Naga",
  "Ozamiz",
  "Pagadian",
  "Puerto Princesa",
  "Roxas",
  "San Jose (Mindoro)",
  "Siargao",
  "Surigao",
  "Tacloban",
  "Tawi-Tawi",
  "Tuguegarao",
  "Virac",
  "Zamboanga",
];

export const SEED_INTERNATIONAL_AIRPORTS = ["Ho Chi Minh", "Hanoi", "Than Hoa"];

export const SEED_AIRPORTS = [...SEED_DOMESTIC_AIRPORTS, ...SEED_INTERNATIONAL_AIRPORTS];

export const SEED_AIRLINES = ["Air Asia", "Cebu Pacific", "PAL"];

export const SEED_BAGGAGE = [
  "7 kg (Hand Carry Only)",
  "20 kg",
  "30 kg",
  "40 kg",
  "50 kg",
];

export const SEED_REIMBURSEMENT_COST_CENTERS = [
  "ADMINISTRATIVE FUNCTIONS",
  "CONTROLLING DEPT",
  "CORPORATE MANAGEMENT",
  "CREDIT & COLLECTION",
  "CUSTOMER SERVICE DEPARTMENT",
  "FORMULATION",
  "HUMAN RESOURCES",
  "INFORMATION TECHNOLOGY",
  "INTERNAL AUDIT",
  "LOGISTICS",
  "MAINTENANCE TEAM",
  "MARKETING",
  "PRODUCTION DIRECT LABOR",
  "PRODUCTION INDIRECT LABOR",
  "PRODUCTION MANAGEMENT",
  "PURCHASING",
  "QUALITY ASSURANCE",
  "REGULATORY & COMPLIANCE",
  "SALES - ALL EMPLOYEES",
  "SALES ADMIN",
  "SUPPLY CHAIN MANAGEMENT",
  "TREASURY DEPT",
  "WAREHOUSE",
];

export const SEED_REIMBURSEMENT_FORM_TYPES = [
  "CA Liquidation",
  "Expense Reimbursement",
  "RF Replenishment",
  "RF Setup Request",
];

export const SEED_REIMBURSEMENT_LOCATIONS = [
  "ALL LUZON",
  "ALL MINDANAO",
  "ALL VISAYAS",
  "ARGAO CEBU PLANT",
  "BACOLOD WAREHOUSE",
  "BUKIDNON PLANT",
  "BULACAN PLANT",
  "CDO WAREHOUSE & TOLLING",
  "CEBEX OFFICE",
  "CENTRAL CEBU SALES",
  "CENTRAL LUZON SALES",
  "CENTRAL MINDANAO SALES",
  "CENTRAL VISAYAS - SALES",
  "CONSOLACION PLANT",
  "EASTERN VISAYAS - SALES",
  "ISABELA PLANT",
  "MAKATI OFFICE",
  "NORTH CEBU SALES",
  "NORTH LUZON SALES",
  "NORTHERN MINDANAO SALES",
  "PFMC MANILA TOLLING",
  "SAN GABRIEL BULACAN WH",
  "SOUTH CEBU - SALES",
  "SOUTH LUZON - SALES",
  "SOUTHERN MINDANDAO",
  "WESTERN MINDANAO",
  "WESTERN VISAYAS",
];

export const SEED_REIMBURSEMENT_ROUTES: Array<{
  department: string;
  costCenter: string;
  location: string;
  supervisorEmail: string;
  supervisorName: string;
  headEmail: string;
  headName: string;
}> = [
  {
    department: "Admin & Finance",
    costCenter: "ADMINISTRATIVE FUNCTIONS",
    location: "ALL LUZON",
    supervisorEmail: "aileen.guerrero@vienovo.ph",
    supervisorName: "Aileen Guerrero",
    headEmail: "aileen.guerrero@vienovo.ph",
    headName: "Aileen Guerrero",
  },
  {
    department: "Audit",
    costCenter: "CONTROLLING DEPT",
    location: "ALL MINDANAO",
    supervisorEmail: "alec.ade@vienovo.ph",
    supervisorName: "Alec Alliage Ade",
    headEmail: "alec.ade@vienovo.ph",
    headName: "Alec Alliage Ade",
  },
  {
    department: "Eurolab",
    costCenter: "CORPORATE MANAGEMENT",
    location: "ALL VISAYAS",
    supervisorEmail: "alvin.arnibal@vienovo.ph",
    supervisorName: "Alvin Arnibal",
    headEmail: "angelica.cosico@vienovo.ph",
    headName: "Angelica Cosico",
  },
  {
    department: "Formulation & Qlty Assurance",
    costCenter: "CREDIT & COLLECTION",
    location: "ARGAO CEBU PLANT",
    supervisorEmail: "angelica.cosico@vienovo.ph",
    supervisorName: "Angelica Cosico",
    headEmail: "carminda.calderon@vienovo.ph",
    headName: "Carminda Calderon",
  },
  {
    department: "IT",
    costCenter: "CUSTOMER SERVICE DEPARTMENT",
    location: "BACOLOD WAREHOUSE",
    supervisorEmail: "bono.arceo@vienovo.ph",
    supervisorName: "Bono John Arceo",
    headEmail: "charo@vienovo.ph",
    headName: "Charo Abadilla",
  },
  {
    department: "Logistics",
    costCenter: "FORMULATION",
    location: "BUKIDNON PLANT",
    supervisorEmail: "carminda.calderon@vienovo.ph",
    supervisorName: "Carminda Calderon",
    headEmail: "christophe.romelard@vienovo.ph",
    headName: "Christophe Romelard",
  },
  {
    department: "Marketing",
    costCenter: "HUMAN RESOURCES",
    location: "BULACAN PLANT",
    supervisorEmail: "charo@vienovo.ph",
    supervisorName: "Charo Abadilla",
    headEmail: "emily.ejoc@vienovo.ph",
    headName: "Emily Ejoc",
  },
  {
    department: "Production&Warehouse",
    costCenter: "INFORMATION TECHNOLOGY",
    location: "CDO WAREHOUSE & TOLLING",
    supervisorEmail: "cheralyn.villaflor@vienovo.ph",
    supervisorName: "Cheralyn Villaflor - Mindanao",
    headEmail: "joel.durano@vienovo.ph",
    headName: "Dominador Durano",
  },
  {
    department: "Purchasing",
    costCenter: "INTERNAL AUDIT",
    location: "CEBEX OFFICE",
    supervisorEmail: "christophe.romelard@vienovo.ph",
    supervisorName: "Christophe Romelard",
    headEmail: "marvin@vienovo.ph",
    headName: "Marvin Rosario",
  },
  {
    department: "QA",
    costCenter: "LOGISTICS",
    location: "CENTRAL CEBU SALES",
    supervisorEmail: "cris-ann.urtezuela@vienovo.ph",
    supervisorName: "Cris-Ann Urtezuela",
    headEmail: "mathieu@vienovo.ph",
    headName: "Mathieu Guillaume",
  },
  {
    department: "Sales",
    costCenter: "MAINTENANCE TEAM",
    location: "CENTRAL LUZON SALES",
    supervisorEmail: "edfrey.buenaventura@vienovo.ph",
    supervisorName: "Edfrey Buenaventura",
    headEmail: "rachel@vienovo.ph",
    headName: "Rachel Remulta",
  },
  // Sales (continued rows in the sheet)
  {
    department: "Sales",
    costCenter: "MARKETING",
    location: "CENTRAL MINDANAO SALES",
    supervisorEmail: "edward.josol@vienovo.ph",
    supervisorName: "Edward Josol",
    headEmail: "ramil.blancaflor@vienovo.ph",
    headName: "Ramil Blancaflor",
  },
  {
    department: "Sales",
    costCenter: "PRODUCTION DIRECT LABOR",
    location: "CENTRAL VISAYAS - SALES",
    supervisorEmail: "emily.ejoc@vienovo.ph",
    supervisorName: "Emily Ejoc",
    headEmail: "richard.lagdaan@vienovo.ph",
    headName: "Richard Lagdaan",
  },
  {
    department: "Sales",
    costCenter: "PRODUCTION INDIRECT LABOR",
    location: "CONSOLACION PLANT",
    supervisorEmail: "eric.salazar@vienovo.ph",
    supervisorName: "Eric Salazar",
    headEmail: "teza@vienovo.ph",
    headName: "Tereza Guillaume",
  },
  {
    department: "Sales",
    costCenter: "PRODUCTION MANAGEMENT",
    location: "EASTERN VISAYAS - SALES",
    supervisorEmail: "francis.gestopa@vienovo.ph",
    supervisorName: "Francis Gestopa",
    headEmail: "yoann.nohe@vienovo.ph",
    headName: "Yoann Nohe",
  },
  {
    department: "Sales",
    costCenter: "PURCHASING",
    location: "ISABELA PLANT",
    supervisorEmail: "joe.eyoy@vienovo.ph",
    supervisorName: "Joe Patrick Eyoy",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "QUALITY ASSURANCE",
    location: "MAKATI OFFICE",
    supervisorEmail: "joel.durano@vienovo.ph",
    supervisorName: "Dominador Durano",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "REGULATORY & COMPLIANCE",
    location: "NORTH CEBU SALES",
    supervisorEmail: "keemeelyn.grimpula@vienovo.ph",
    supervisorName: "Keemeelyn Grimpula",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "SALES - ALL EMPLOYEES",
    location: "NORTH LUZON SALES",
    supervisorEmail: "lian.urriza@vienovo.ph",
    supervisorName: "Lian Urriza - Luzon",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "SALES ADMIN",
    location: "NORTHERN MINDANAO SALES",
    supervisorEmail: "mart.espliguez@vienovo.ph",
    supervisorName: "Mart Espliguez",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "SUPPLY CHAIN MANAGEMENT",
    location: "PFMC MANILA TOLLING",
    supervisorEmail: "marvin@vienovo.ph",
    supervisorName: "Marvin Rosario",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "TREASURY DEPT",
    location: "SAN GABRIEL BULACAN WH",
    supervisorEmail: "mathieu@vienovo.ph",
    supervisorName: "Mathieu Guillaume",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "WAREHOUSE",
    location: "SOUTH CEBU - SALES",
    supervisorEmail: "michelle.palad@vienovo.ph",
    supervisorName: "Michelle Ann Palad",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "WAREHOUSE",
    location: "SOUTH LUZON - SALES",
    supervisorEmail: "rachel@vienovo.ph",
    supervisorName: "Rachel Remulta",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "WAREHOUSE",
    location: "SOUTHERN MINDANDAO",
    supervisorEmail: "ramil.blancaflor@vienovo.ph",
    supervisorName: "Ramil Blancaflor",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "WAREHOUSE",
    location: "WESTERN MINDANAO",
    supervisorEmail: "rddabu@vienovo.ph",
    supervisorName: "Reggie Dabu",
    headEmail: "",
    headName: "",
  },
  {
    department: "Sales",
    costCenter: "WAREHOUSE",
    location: "WESTERN VISAYAS",
    supervisorEmail: "richard.lagdaan@vienovo.ph",
    supervisorName: "Richard Lagdaan",
    headEmail: "",
    headName: "",
  },
];

type SeedApprover = {
  name: string;
  email: string;
  roles: ("supervisor" | "head" | "processor" | "cashAdvanceApprover")[];
  emailNeedsReview: boolean;
};

// People who handle the final processor step in the approval chain
// (submitter → supervisor → head → processor). Temporary testing roster —
// flip back to the real Finance/Admin team before production.
export const SEED_APPROVERS: SeedApprover[] = [
  // Travel Booking supervisors/heads (step 1 + step 2)
  { name: "Aileen Guerrero", email: "aileen.guerrero@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Angelica Cosico", email: "angelica.cosico@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Charo Abadilla", email: "charo@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Christophe Romelard", email: "christophe.romelard@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Edmund Monisit", email: "edmund.monisit@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Joel Durano", email: "joel.durano@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Marvin Rosario", email: "marvin@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Mathieu Guillaume", email: "mathieu@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Rachel Remulta", email: "rachel@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Ramil Blancaflor", email: "ramil.blancaflor@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Reggie Dabu", email: "rddabu@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Tereza Guillaume", email: "teza@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Yoann Nohe", email: "yoann.nohe@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Ronyl Saranillo", email: "ronyl.saranillo@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Cheralyn Villaflor - Mindanao", email: "cheralyn.villaflor@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Lian Urriza - Luzon", email: "lian.urriza@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Shannien Llavore", email: "shannien.llavore@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Jerome Corpus", email: "jerome.corpus@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },

  // Reimbursement routing (additional supervisors/heads seen in the sheet)
  { name: "Alec Alliage Ade", email: "alec.ade@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Alvin Arnibal", email: "alvin.arnibal@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Bono John Arceo", email: "bono.arceo@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Carminda Calderon", email: "carminda.calderon@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Cris-Ann Urtezuela", email: "cris-ann.urtezuela@vienovo.ph", roles: ["supervisor", "head"], emailNeedsReview: false },
  { name: "Dominador Durano", email: "joel.durano@vienovo.ph", roles: ["head"], emailNeedsReview: true },
  { name: "Edward Josol", email: "edward.josol@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Edfrey Buenaventura", email: "edfrey.buenaventura@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Eric Salazar", email: "eric.salazar@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Francis Gestopa", email: "francis.gestopa@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Keemeelyn Grimpula", email: "keemeelyn.grimpula@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },
  { name: "Michelle Ann Palad", email: "michelle.palad@vienovo.ph", roles: ["supervisor"], emailNeedsReview: false },

  // Final approver / processor (step 3)
  { name: "Ricky Dave Mundia", email: "dave.mundia@vienovo.ph", roles: ["processor"], emailNeedsReview: false },

  // Cash Advance approvers (single approval step before processor)
  { name: "Aileen Guerrero", email: "aileen.guerrero@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Alec Alliage Ade", email: "alec.ade@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Carminda Calderon", email: "carminda.calderon@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Charo Abadilla", email: "charo@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Christophe Romelard", email: "christophe.romelard@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Cris-Ann Urtezuela", email: "cris-ann.urtezuela@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Edfrey Buenaventura", email: "edfrey.buenaventura@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Emily Ejoc", email: "emily.ejoc@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Eric Salazar", email: "eric.salazar@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Joe Patrick Eyoy", email: "Joe.Eyoy@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Joel Durano", email: "joel.durano@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Kenneth Lacson", email: "kenneth.lacson@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Lian Urizza for Luzon", email: "lian.urriza@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Mart Espliguez", email: "mart.espliguez@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Marvin Rosario", email: "marvin@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Mathieu Guillaume", email: "mathieu@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Rachel Remulta", email: "rachel@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Ramil Blancaflor", email: "ramil.blancaflor@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Reggie Dabu", email: "rddabu@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Richard Lagdaan", email: "richard.lagdaan@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Ronyl Saranillo - Visayas", email: "ronyl.saranillo@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Cheralyn Villaflor - Mindanao", email: "cheralyn.villaflor@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Edward Josol", email: "edward.josol@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Yoann Nohe", email: "yoann.nohe@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
  { name: "Shannien Llavore", email: "shannien.llavore@vienovo.ph", roles: ["cashAdvanceApprover"], emailNeedsReview: false },
];
